package components.regions.types

enum class RegionFlag {
  PUBLIC,
  ENABLE_EXPLOSIONS,
  ENABLE_FIRE_DAMAGE,
  ENABLE_PUBLIC_CONTAINERS,
  DISABLE_ANIMAL_PROTECTION,
  DISABLE_GATES,
  DISABLE_PLAYER_FALL_DAMAGE,
  ADMIN,
  ENABLE_PUBLIC_VILLAGER_TRADING,
  DISABLE_PUBLIC_REDSTONE_TRIGGERS;
}